advert_index:
    path:     /
    defaults: { _controller: "LoicCMSBundle:Advert:index" }
    methods:  GET

advert_show:
    path:     /{id}/show
    defaults: { _controller: "LoicCMSBundle:Advert:show" }
    methods:  GET

advert_new:
    path:     /new
    defaults: { _controller: "LoicCMSBundle:Advert:new" }
    methods:  [GET, POST]

advert_edit:
    path:     /{id}/edit
    defaults: { _controller: "LoicCMSBundle:Advert:edit" }
    methods:  [GET, POST]

advert_delete:
    path:     /{id}/delete
    defaults: { _controller: "LoicCMSBundle:Advert:delete" }
    methods:  DELETE
