loic_cms_advert:
    resource: "@LoicCMSBundle/Resources/config/routing/advert.yml"
    prefix:   /admin/advert

loic_cms_category:
    resource: "@LoicCMSBundle/Resources/config/routing/category.yml"
    prefix:   /admin/category

loic_cms_homepage:
    path:     /
    defaults: { _controller: LoicCMSBundle:Default:index }

advert_view:
    path:     /{category}/{slug}
    defaults: { _controller: "LoicCMSBundle:Advert:view" }

advert_revert:
    path:     /admin/revert/advert={advert}/version={version}
    defaults: { _controller: "LoicCMSBundle:Advert:revert" }

category_view:
    path:     /categorie/advert-list/{slug}
    defaults: { _controller: "LoicCMSBundle:Category:view" }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile