<?php

namespace Loic\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Loic\CMSBundle\Entity\Category;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategory($category)
    {
        $qb =  $this->createQueryBuilder('a');

        $qb
            ->select('a')
            ->leftJoin('a.categories', 'c')
            ->addSelect('c')
            ->where('a.firstCategory = :cf OR c = :c')
            ->setParameters(array('cf' => $category, 'c' => $category))
            ->groupBy('a.title');

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}