<?php

namespace Loic\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategories($category)
    {
        $qb =  $this->createQueryBuilder('a');

        $qb
            ->select('a')
            ->where('a.firstCategory = :c')
            ->setParameter(':c', $category)
            ;

        $qb
            ->getQuery()
            ->getResult();
        return $qb;
    }
}

   /* ->leftJoin('a.categories', 'c')
    ->addSelect('c')
    ->where('cf = :cf OR c = :c')
    ->setParameters(array('cf' => $category, 'c' => $category))*/